"""
Generacion de codigo para la API: app.py, models.py, requirements.txt,
Dockerfile, README.md, tests/test_app.py.

Cada funcion toma el FuncInfo + opciones y devuelve un string con el
codigo fuente. NO escribe a disco (eso lo hace build.py).
"""

from __future__ import annotations

from .analyze import AnalyzeResult, FuncInfo, ParamInfo


def generate_pydantic_model(info: AnalyzeResult, model_name: str = "InputModel") -> str:
    """Genera el codigo Python del modelo pydantic a partir de los params."""
    fields = []
    for p in info.func.params:
        ann = p.annotation or "Any"
        if p.required:
            fields.append(f"    {p.name}: {ann}")
        else:
            default = _py_default(p.default)
            fields.append(f"    {p.name}: {ann} = {default}")
    body = "\n".join(fields) if fields else "    pass"
    return (
        f"from pydantic import BaseModel, Field\n"
        f"from typing import Any, Optional\n\n\n"
        f"class {model_name}(BaseModel):\n"
        f"{body}\n"
    )


def _py_default(value: object) -> str:
    """Representacion segura de un default value."""
    if value is None:
        return "None"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return repr(value)
    # Para defaults raros (objetos custom), None + warning
    return "None  # type: ignore  # default custom"


def generate_fastapi_app(info: AnalyzeResult, pydantic_code: str,
                         endpoint_name: str | None = None,
                         api_key: str | None = None) -> str:
    """Genera el codigo de app.py con FastAPI."""
    ep = endpoint_name or "predict"
    func = info.func
    has_params = len(func.params) > 0

    # Si no hay params, el endpoint es GET; si hay, POST
    method = "GET" if not has_params else "POST"

    # Construir la llamada a la funcion desde el modelo pydantic
    if has_params:
        kwargs = ", ".join(f"{p.name}=payload.{p.name}" for p in func.params)
    else:
        kwargs = ""

    # Auth opcional
    auth_decorator = ""
    auth_import = ""
    if api_key:
        auth_import = "import os\n"
        auth_decorator = (
            "\n\ndef _require_api_key(x_api_key: str = Header(default='')) -> None:\n"
            "    expected = os.environ.get('API_KEY', '')\n"
            "    if expected and x_api_key != expected:\n"
            "        raise HTTPException(status_code=401, detail='Invalid API key')\n"
        )

    # Documentacion del endpoint (del docstring)
    first_line = (func.docstring or f"Run {func.name} and return its result as JSON.").split("\n")[0]

    return (
        f'"""\nAuto-generated by data-analytics-agents · api-builder\n'
        f'Source: {func.module_path}\n'
        f'Function: {func.qualified_name}\n'
        f'Generated at: see git log\n"""\n'
        f'{auth_import}'
        f'from fastapi import FastAPI, HTTPException\n'
        f'from fastapi import Header\n'
        f'from pydantic import BaseModel\n'
        f'from typing import Any\n'
        f'\n'
        f'import importlib.util\n'
        f'from pathlib import Path\n'
        f'\n'
        f'{pydantic_code}'
        f'\n\n'
        f'app = FastAPI(\n'
        f'    title="{func.name} API",\n'
        f'    description="{first_line}",\n'
        f'    version="0.1.0",\n'
        f')\n'
        f'{auth_decorator}'
        f'\n\n'
        f'# Cargar el modulo de analisis una sola vez al startup\n'
        f'_ANALYSIS_PATH = Path(__file__).parent / "analysis.py"\n'
        f'_spec = importlib.util.spec_from_file_location("_analysis", _ANALYSIS_PATH)\n'
        f'_analysis_mod = importlib.util.module_from_spec(_spec)\n'
        f'_spec.loader.exec_module(_analysis_mod)  # noqa: E402\n'
        f'_func = getattr(_analysis_mod, "{func.name}")\n'
        f'\n\n'
        f'@app.get("/health")\n'
        f'def health() -> dict:\n'
        f'    """Health check endpoint."""\n'
        f'    return {{"status": "ok"}}\n'
        f'\n\n'
        f'@app.{method.lower()}("/{ep}")\n'
        f'{"@_require_api_key" if api_key else ""}\n'
        f'def {ep}(payload: InputModel) -> Any:\n'
        f'    """{first_line}"""\n'
        f'    try:\n'
        f'        result = _func({kwargs})\n'
        f'    except Exception as e:\n'
        f'        raise HTTPException(status_code=500, detail=str(e))\n'
        f'    return result\n'
        f'\n\n'
        f'@app.get("/schema")\n'
        f'def schema() -> dict:\n'
        f'    """Devuelve el input schema como JSON."""\n'
        f'    return InputModel.model_json_schema()\n'
    )


def generate_requirements(info: AnalyzeResult) -> str:
    """Genera requirements.txt: fastapi, uvicorn, pydantic + imports del usuario."""
    deps = [
        "fastapi>=0.110",
        "uvicorn[standard]>=0.27",
        "pydantic>=2.0",
    ]
    deps.extend(info.imports)
    return "\n".join(deps) + "\n"


def generate_dockerfile() -> str:
    return (
        "FROM python:3.11-slim\n"
        "\n"
        "WORKDIR /app\n"
        "\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "\n"
        "COPY . .\n"
        "\n"
        "EXPOSE 8000\n"
        "\n"
        'CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]\n'
    )


def generate_readme(info: AnalyzeResult, endpoint: str = "predict") -> str:
    func = info.func
    params_doc = "\n".join(
        f"- `{p.name}` ({p.annotation}){' — optional' if not p.required else ''}"
        for p in func.params
    ) or "(no parameters)"
    return (
        f"# {func.name} API\n"
        f"\n"
        f"Auto-generated by `data-analytics-agents` · `api-builder`.\n"
        f"\n"
        f"Source function: `{func.qualified_name}` ({func.module_path})\n"
        f"\n"
        f"## Run locally\n"
        f"\n"
        f"```bash\n"
        f"pip install -r requirements.txt\n"
        f"uvicorn app:app --reload\n"
        f"```\n"
        f"\n"
        f"Then open http://localhost:8000/docs for Swagger UI.\n"
        f"\n"
        f"## Endpoints\n"
        f"\n"
        f"- `GET /health` — health check\n"
        f"- `GET /schema` — JSON schema of the input\n"
        f"- `POST /{endpoint}` — run {func.name}\n"
        f"\n"
        f"## Input parameters\n"
        f"\n"
        f"{params_doc}\n"
        f"\n"
        f"## Deploy\n"
        f"\n"
        f"```bash\n"
        f"docker build -t {func.name}-api .\n"
        f"docker run -p 8000:8000 {func.name}-api\n"
        f"```\n"
        f"\n"
        f"## Auth (optional)\n"
        f"\n"
        f"Set `API_KEY` env var to require the `X-API-Key` header. If not set, the API is open (dev only).\n"
        f"\n"
        f"```bash\n"
        f"export API_KEY=tu-clave-secreta\n"
        f"uvicorn app:app\n"
        f"```\n"
    )


def generate_tests(info: AnalyzeResult, endpoint: str = "predict") -> str:
    func = info.func
    has_params = len(func.params) > 0
    # Construir un payload de ejemplo usando defaults si los hay
    example_payload = {}
    for p in func.params:
        if p.default is not None:
            example_payload[p.name] = p.default
        elif p.annotation in ("int", "float"):
            example_payload[p.name] = 0
        elif p.annotation == "str":
            example_payload[p.name] = "test"
        elif p.annotation == "bool":
            example_payload[p.name] = False
        else:
            example_payload[p.name] = None

    import json
    payload_str = json.dumps(example_payload, indent=8, default=str)
    # json.dumps emite 'true'/'false'/'null' (JS); el test es Python — fix.
    payload_str = payload_str.replace(": true", ": True").replace(": false", ": False").replace(": null", ": None")
    if has_params:
        call_line = f'r = client.post("/{endpoint}", json=payload)'
    else:
        call_line = f'r = client.get("/{endpoint}")'
    return (
        f'"""\nSmoke tests auto-generated for {func.qualified_name}.\n"""\n'
        f'from fastapi.testclient import TestClient\n'
        f'from app import app\n'
        f'\n'
        f'client = TestClient(app)\n'
        f'\n'
        f'\n'
        f'def test_health() -> None:\n'
        f'    r = client.get("/health")\n'
        f'    assert r.status_code == 200\n'
        f'    assert r.json() == {{"status": "ok"}}\n'
        f'\n'
        f'\n'
        f'def test_schema() -> None:\n'
        f'    r = client.get("/schema")\n'
        f'    assert r.status_code == 200\n'
        f'    assert "properties" in r.json()\n'
        f'\n'
        f'\n'
        f'def test_{endpoint}() -> None:\n'
        f'    payload = {payload_str}\n'
        f'    {call_line}\n'
        f'    assert r.status_code == 200, r.text\n'
        f'    # El body exacto depende de la funcion del usuario — no assert sobre keys\n'
        f'    assert r.json() is not None\n'
    )